document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id),state={photos:[],canvases:[]};
const themes={cream:{bg:'#F7F0DF',ink:'#17213A',accent:'#F5C84B',soft:'#FFF9EC'},navy:{bg:'#111B36',ink:'#FFFFFF',accent:'#F2CC4D',soft:'#26385E'},summer:{bg:'#E8F8FF',ink:'#12355B',accent:'#FFD858',soft:'#FFFFFF'}};
const status=$('status');
$('photos').addEventListener('change',async e=>{const files=[...e.target.files].slice(0,10-state.photos.length);for(const f of files){try{const url=URL.createObjectURL(f),img=await loadImage(url);state.photos.push({url,img})}catch(err){console.error(err)}}renderPhotos();e.target.value=''});
document.querySelectorAll('.template').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('.template').forEach(x=>x.classList.remove('active'));el.classList.add('active')}));
$('generateBtn').onclick=()=>{status.textContent='アルバムを作成中…';setTimeout(generateAlbum,20)};
$('downloadAllBtn').onclick=async()=>{for(let i=0;i<state.canvases.length;i++){download(state.canvases[i],`my-story-${String(i+1).padStart(2,'0')}.png`);await new Promise(r=>setTimeout(r,250))}};
function renderPhotos(){$('photoList').innerHTML='';state.photos.forEach((p,i)=>{const d=document.createElement('div');d.className='photo-thumb';const im=document.createElement('img');im.src=p.url;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{URL.revokeObjectURL(p.url);state.photos.splice(i,1);renderPhotos()};d.append(im,b);$('photoList').appendChild(d)})}
function generateAlbum(){try{const name=$('name').value.trim()||'MY STORY',subtitle=$('subtitle').value.trim()||'PERSONAL MEMORIES',school=$('school').value.trim()||'プロフィールを入力してください',hobby=$('hobby').value.trim()||'好きなことを入力してください',message=$('message').value.trim()||'これからも、たくさんの思い出を。',friendMessage=$('friendMessage').value.trim()||'あなたらしい毎日が、もっと素敵になりますように。',theme=themes[document.querySelector('input[name="template"]:checked').value],count=Number($('pageCount').value),story=$('ratio').value==='story',W=720,H=story?1280:900,d={name,subtitle,school,hobby,message,friendMessage,theme,W,H};state.canvases=[];$('preview').className='preview-grid';$('preview').innerHTML='';for(let i=0;i<count;i++){const c=document.createElement('canvas');c.width=W;c.height=H;drawPage(c,i,count,d);state.canvases.push(c);const card=document.createElement('div');card.className='page-card';card.appendChild(c);const a=document.createElement('div');a.className='page-actions';const s=document.createElement('span');s.textContent=`${i+1} / ${count}`;const b=document.createElement('button');b.className='download-btn';b.textContent='PNG保存';b.onclick=()=>download(c,`my-story-${String(i+1).padStart(2,'0')}.png`);a.append(s,b);card.appendChild(a);$('preview').appendChild(card)}status.textContent=`${count}枚のアルバムを作成しました。`;$('downloadAllBtn').disabled=false;$('preview').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){console.error(err);status.textContent='作成エラー：'+(err.message||err)}}
function drawPage(canvas,i,total,d){const c=canvas.getContext('2d'),{W,H,theme}=d;c.fillStyle=theme.bg;c.fillRect(0,0,W,H);c.fillStyle=theme.accent;c.beginPath();c.arc(W-70,70,46,0,Math.PI*2);c.fill();c.fillStyle=theme.ink;c.font='700 20px sans-serif';c.fillText(String(i+1).padStart(2,'0'),35,45);if(i===0)cover(c,d);else if(i===1)profile(c,d);else if(i===total-1)closing(c,d);else memory(c,d,i)}
function cover(c,d){const {W,H,theme}=d;photoOrBox(c,state.photos[0],50,85,W-100,H*.60,28,theme);c.fillStyle=theme.ink;c.font='800 25px sans-serif';c.fillText(d.subtitle.toUpperCase(),55,H*.76);c.font='900 62px sans-serif';wrap(c,d.name,55,H*.85,W-110,68);c.fillStyle=theme.accent;c.fillRect(55,H-60,170,10)}
function profile(c,d){const {W,H,theme}=d;c.fillStyle=theme.ink;c.font='900 48px sans-serif';c.fillText('ABOUT ME',50,105);photoOrBox(c,state.photos[1]||state.photos[0],50,145,W*.42,H*.46,25,theme);const x=W*.55;c.font='800 20px sans-serif';c.fillText('NAME',x,190);c.font='900 34px sans-serif';wrap(c,d.name,x,235,W*.38,40);c.font='800 20px sans-serif';c.fillText('SCHOOL',x,375);c.font='600 25px sans-serif';wrap(c,d.school,x,415,W*.38,34);c.font='800 20px sans-serif';c.fillText('FAVORITE',x,545);c.font='600 25px sans-serif';wrap(c,d.hobby,x,585,W*.38,34);roundRect(c,50,H-205,W-100,140,22);c.fillStyle=theme.soft;c.fill();c.fillStyle=theme.ink;c.font='600 25px sans-serif';wrap(c,d.message,80,H-155,W-160,36)}
function memory(c,d,i){const {W,H,theme}=d;c.fillStyle=theme.ink;c.font='900 46px sans-serif';c.fillText(i%2?'MEMORY':'MY MOMENT',50,105);const p=state.photos[(i-2)%Math.max(1,state.photos.length)];photoOrBox(c,p,50,145,W-100,H-280,25,theme);c.font='700 20px sans-serif';c.fillText(`${d.name} • PAGE ${i+1}`,55,H-70)}
function closing(c,d){const {W,H,theme}=d;c.fillStyle=theme.ink;c.font='900 52px sans-serif';wrap(c,'TO BE CONTINUED.',50,125,W-100,60);photoOrBox(c,state.photos[state.photos.length-1],50,235,W-100,H*.40,28,theme);roundRect(c,50,H*.72,W-100,H*.16,22);c.fillStyle=theme.soft;c.fill();c.fillStyle=theme.ink;c.font='700 25px sans-serif';wrap(c,d.friendMessage,80,H*.77,W-160,36)}
function photoOrBox(c,p,x,y,w,h,r,t){roundRect(c,x,y,w,h,r);c.save();c.clip();if(p){const img=p.img,ir=img.width/img.height,br=w/h;let sx=0,sy=0,sw=img.width,sh=img.height;if(ir>br){sw=img.height*br;sx=(img.width-sw)/2}else{sh=img.width/br;sy=(img.height-sh)/2}c.drawImage(img,sx,sy,sw,sh,x,y,w,h)}else{c.fillStyle=t.soft;c.fillRect(x,y,w,h);c.fillStyle=t.ink;c.globalAlpha=.35;c.font='700 24px sans-serif';c.textAlign='center';c.fillText('ADD YOUR PHOTO',x+w/2,y+h/2);c.textAlign='start';c.globalAlpha=1}c.restore()}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.lineTo(x+w-r,y);c.quadraticCurveTo(x+w,y,x+w,y+r);c.lineTo(x+w,y+h-r);c.quadraticCurveTo(x+w,y+h,x+w-r,y+h);c.lineTo(x+r,y+h);c.quadraticCurveTo(x,y+h,x,y+h-r);c.lineTo(x,y+r);c.quadraticCurveTo(x,y,x+r,y);c.closePath()}
function wrap(c,text,x,y,max,lineH){let line='';for(const ch of [...text]){const test=line+ch;if(line&&c.measureText(test).width>max){c.fillText(line,x,y);line=ch;y+=lineH}else line=test}if(line)c.fillText(line,x,y)}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('画像を読み込めません'));i.src=src})}
function download(c,name){const a=document.createElement('a');a.download=name;a.href=c.toDataURL('image/png');document.body.appendChild(a);a.click();a.remove()}
});